language: python
python:
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libatlas-base-dev liblapack-dev gfortran
script:
  - pip install -e .
  - python setup.py install 
  - vturra 11 cs
